### ISSUE TITLE
Square brackets in columns parameters, should be list?

### ISSUE THREAD

**Issue by nicmar** [andrey-git/home-assistant-customizer#3]
The code on this page (https://github.com/andrey-git/home-assistant-customizer/):

`columns: 350, 700, 1050, 1400, 1850, 2100`

Doesn't seem to work, when I check config says it needs a list. When I changed it to:
`columns: [350, 700, 1050, 1400, 1850, 2100]`

The config was accepted. However I don't see any changes to any of my cards, after I added this to the config:

```
homeassistant:
  customize_glob:
    "*.*":
       custom_ui_state_card: state-card-custom-ui

customizer:
  custom_ui: local
  columns: [500, 1000, 1500, 2000, 2500, 3000, 3500]
```

Did I miss something?
